apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - deployment.yaml
  # Create secrets.yaml from secrets.template.yaml and encrypt with SOPS
  # - secrets.enc.yaml
