apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
  namespace: security
spec:
  interval: 1h
  chart:
    spec:
      chart: tetragon
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: isovalent
        namespace: flux-system
  values:
    tetragon:
      enableProcessCred: true
      enableProcessNs: true
      exportFilename: "tetragon.log"
    export:
      stdout:
        enabled: true
