apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - oci-registry-secret.yaml
  - audiobookshelf/base
  - lidarr/base
  - navidrome/base
  - networkpolicy.yaml
