apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-registry
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: oci-registry
    creationPolicy: Owner
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: OCIR_DOCKER_CONFIG
