apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: security
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.1

  storage:
    size: 10Gi
    storageClass: oci-bv

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-app

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "64MB"
