apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 1h
  releaseName: authentik
  chart:
    spec:
      chart: authentik
      version: "2024.12.0"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    # Deprecated: ingress key removed as per 2024.12.0 chart
    postgresql:
      enabled: true
    redis:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_POSTGRES_PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_REDIS_PASSWORD
      targetPath: authentik.redis.password
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_POSTGRES_PASSWORD
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_REDIS_PASSWORD
      targetPath: redis.auth.password
    - kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_BOOTSTRAP_TOKEN
      targetPath: authentik.bootstrap_token
