apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - database.yaml
  - external-secret.yaml
  - external-secret-db.yaml
  - helmrelease.yaml
  - ingress.yaml
