apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  # Policies require Kyverno to be installed first
  # Uncomment after Kyverno is deployed:
  # - policies/require-labels.yaml
  # - policies/disallow-latest-tag.yaml
  # - policies/disallow-root-user.yaml
