# Velero S3 Credentials Secret
# ENCRYPT THIS FILE WITH SOPS BEFORE COMMITTING!
#
# After running terraform apply, get credentials:
#   terraform output -json velero_s3_credentials
#
# Then encrypt:
#   sops -e credentials.yaml > credentials.enc.yaml
#
apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=REPLACE_WITH_ACCESS_KEY_FROM_TERRAFORM
    aws_secret_access_key=REPLACE_WITH_SECRET_KEY_FROM_TERRAFORM
