apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: outline-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: OUTLINE_SECRET_KEY
    - secretKey: UTILS_SECRET
      remoteRef:
        key: OUTLINE_UTILS_SECRET
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: OUTLINE_OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: OUTLINE_OIDC_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-db-app
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: outline-db-app
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: OUTLINE_DB_URI

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-oci-s3-secrets
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: outline-oci-s3-secrets
    creationPolicy: Owner
  data:
  - secretKey: access_key
    remoteRef:
      key: OCI_S3_ACCESS_KEY
  - secretKey: secret_key
    remoteRef:
      key: OCI_S3_SECRET_KEY
  - secretKey: endpoint_url
    remoteRef:
      key: OCI_S3_ENDPOINT_URL
