# Homarr - Kustomize base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

resources:
  - namespace.yaml
  - rbac.yaml
  - db-secret.yaml
  - helmrelease.yaml
  - ingress.yaml
  - certificate.yaml
  - networkpolicy.yaml
