# n8n - Kustomize base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation

resources:
  - namespace.yaml
  - helmrelease.yaml
  - ingress.yaml
  - certificate.yaml
