apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omni
  namespace: infra
  annotations:
    external-dns.alpha.kubernetes.io/target: "5825ee88-3939-4e16-ab32-856c6ff7df96.cfargotunnel.com"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Omni"
    gethomepage.dev/description: "Talos/K8s Control Plane"
    gethomepage.dev/group: "Administration"
    gethomepage.dev/icon: "talos"
spec:
  rules:
  - host: omni.smadja.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: omni
            port:
              number: 443
