apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
  # bouncer.yaml - disabled, chart not available
  # - bouncer.yaml
