apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-credentials
  namespace: o11y
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: grafana-cloud-credentials
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLOUD_PROM_URL
      remoteRef:
        key: GRAFANA_CLOUD_PROM_URL
    - secretKey: GRAFANA_CLOUD_PROM_USERNAME
      remoteRef:
        key: GRAFANA_CLOUD_PROM_USERNAME
    - secretKey: GRAFANA_CLOUD_LOKI_URL
      remoteRef:
        key: GRAFANA_CLOUD_LOKI_URL
    - secretKey: GRAFANA_CLOUD_LOKI_USERNAME
      remoteRef:
        key: GRAFANA_CLOUD_LOKI_USERNAME
    - secretKey: GRAFANA_CLOUD_API_KEY
      remoteRef:
        key: GRAFANA_CLOUD_API_KEY
