apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/application.yaml
  - cloudflared/application.yaml
  - twingate/application.yaml
  - reloader/application.yaml
  - network-policies/application.yaml
  - velero/application.yaml
  # - external-secrets/application.yaml
