apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1h
  releaseName: tailscale-operator
  chart:
    spec:
      chart: tailscale-operator
      version: "1.78.3"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    oauth:
      secretName: operator-oauth
