apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator-config
  namespace: netbird
spec:
  interval: 1h
  chart:
    spec:
      chart: netbird-operator-config
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: netbirdio
        namespace: flux-system
  values:
    # Activer le routing peer pour exposés les services
    router:
      enabled: true
    # Politique par défaut
    policies:
      default:
        name: Kubernetes Default Policy
        sourceGroups:
          - All
    # Exposer l'API Kubernetes
    kubernetesAPI:
      enabled: true
      groups:
        - k8s-access
      policies:
        - k8s-admins
