apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: netbird-mgmt-api-key
    creationPolicy: Owner
  data:
    - secretKey: NB_API_KEY
      remoteRef:
        key: NETBIRD_API_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-setup-key
  namespace: netbird
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: netbird-setup-key
    creationPolicy: Owner
  data:
    # Utiliser la cl√© locale pour cluster Talos
    # Pour OCI, utiliser NETBIRD_SETUP_KEY_OCI
    - secretKey: setup_key
      remoteRef:
        key: NETBIRD_SETUP_KEY_LOCAL
