apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
  namespace: netbird
spec:
  interval: 1h
  chart:
    spec:
      chart: kubernetes-operator
      version: "0.2.1"
      sourceRef:
        kind: HelmRepository
        name: netbirdio
        namespace: flux-system
  values:
    netbirdAPI:
      keyFromSecret:
        name: netbird-mgmt-api-key
        key: NB_API_KEY
  install:
    createNamespace: true
  upgrade:
    createNamespace: true
