storage:
  kind: etcd
  etcd:
    embedded: true
  default:
    kind: etcd
    etcd:
      privateKeySource: builtin
  sqlite:
    path: /var/lib/omni/omni.db
auth:
  enabled: false
server:
  advertisedAddress: http://localhost:8080
account:
  id: 741b2b7c-3b3d-4fd6-8945-b78a40f78283
