apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-secrets
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: vikunja-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: VIKUNJA_JWT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-db-app
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: vikunja-db-app
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: VIKUNJA_DB_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-oci-s3-secrets
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: vikunja-oci-s3-secrets
    creationPolicy: Owner
  data:
  - secretKey: access_key
    remoteRef:
      key: OCI_S3_ACCESS_KEY
  - secretKey: secret_key
    remoteRef:
      key: OCI_S3_SECRET_KEY
  - secretKey: endpoint_url
    remoteRef:
      key: OCI_S3_ENDPOINT_URL
