apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-creds
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflared-creds
    template:
      type: Opaque
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_ID }}",
            "TunnelID": "{{ .CLOUDFLARE_TUNNEL_ID }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}"
          }
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: CLOUDFLARE_ACCOUNT_ID
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: CLOUDFLARE_TUNNEL_ID
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: CLOUDFLARE_TUNNEL_SECRET
