# Cloudflared Kustomize base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
  - namespace.yaml
  - external-secret.yaml
  - configmap.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - pdb.yaml
