apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: external-dns-secrets
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
