apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  targetNamespace: external-dns
  interval: 1h
  timeout: 10m
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    provider: cloudflare
    cloudflare:
      proxied: true
    sources:
      - ingress
      - gateway-httproute
    policy: sync
    txtOwnerId: "external-dns"
    domainFilters:
      - "smadja.dev"
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secrets
            key: CLOUDFLARE_API_TOKEN
  install:
    createNamespace: true
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    force: false
    remediation:
      retries: 3
      remediateLastFailure: true
  driftDetection:
    mode: enabled
