apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiobookshelf-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: audiobookshelf-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUDIOBOOKSHELF_API_KEY
      remoteRef:
        key: AUDIOBOOKSHELF_API_KEY
