apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
  namespace: public
spec:
  secretName: homepage-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - home.smadja.dev
