apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: odoo
  namespace: business
spec:
  interval: 1h
  chart:
    spec:
      chart: odoo
      version: "22.2.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Requires PostgreSQL
    postgresql:
      install: true
    odooPassword: "admin" # Replace via secret in production
