# Cloudflared - Cloudflare Tunnel connector
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SmadjaPaul/homelab.git
    targetRevision: main
    path: kubernetes/infrastructure/cloudflared/manifests
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
