apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: umami-db
  namespace: business
spec:
  instances: 1
  storage:
    size: 1Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://database-backups/umami
      endpointURL: https://<your-namespace>.compat.objectstorage.eu-paris-1.oraclecloud.com
      s3Credentials:
        accessKeyId:
          name: umami-oci-s3-secrets
          key: access_key
        secretAccessKey:
          name: umami-oci-s3-secrets
          key: secret_key
      wal:
        compression: gzip
