apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secrets
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: umami-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: UMAMI_APP_SECRET

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-db-app
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: umami-db-app
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: UMAMI_DB_URI

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-oci-s3-secrets
  namespace: business
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: umami-oci-s3-secrets
    creationPolicy: Owner
  data:
  - secretKey: access_key
    remoteRef:
      key: OCI_S3_ACCESS_KEY
  - secretKey: secret_key
    remoteRef:
      key: OCI_S3_SECRET_KEY
  - secretKey: endpoint_url
    remoteRef:
      key: OCI_S3_ENDPOINT_URL
