apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami
  namespace: business
  annotations:
    external-dns.alpha.kubernetes.io/target: "5825ee88-3939-4e16-ab32-856c6ff7df96.cfargotunnel.com"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Umami"
    gethomepage.dev/description: "Privacy Web Analytics"
    gethomepage.dev/group: "Productivity"
    gethomepage.dev/icon: "umami"
spec:
  rules:
  - host: umami.smadja.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: umami
            port:
              number: 3000
