apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/target: "5825ee88-3939-4e16-ab32-856c6ff7df96.cfargotunnel.com"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Navidrome"
    gethomepage.dev/description: "Music Streaming"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "navidrome"
    gethomepage.dev/widget.type: "navidrome"
    gethomepage.dev/widget.url: "https://navidrome.smadja.dev"
spec:
  rules:
  - host: navidrome.smadja.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: navidrome
            port:
              number: 4533
